In [11]:
class Car:
    def __init__(self,brand,model,year):
        self.brand=brand
        self.model=model
        self.year=year

carl=Car("BMW","M5 Competition",2019)
print(carl.brand)
print(carl.model)
print(carl.year)


BMW
M5 Competition
2019


In [18]:
# Encapsulation ka example h
class bankaccount:
    def __init__(self,salary):
        self.salary=salary
    def  withdraw(self,amount):
        self.salary-=amount
        return self.salary
    def addsalary(self,amount):
        self.salary+=amount
        return self.salary
    def getbalance(self):
        return self.salary
employee1=bankaccount(10000)
print("Balance is :",employee1.getbalance())
print(employee1.addsalary(1000))
print("Balance is :",employee1.getbalance())
print(employee1.withdraw(500))
print("Balance is :",employee1.getbalance())
employee1=bankaccount(1000000000000)
print("Balance is :",employee1.getbalance())

Balance is : 10000
11000
Balance is : 11000
10500
Balance is : 10500
Balance is : 1000000000000


In [19]:
#Inheritance ka example
class animal:
    def sound(self):
        print("I am an animal")
class dog(animal):
    def sound(self):
        print("Bark")
c=dog()
c.sound()

Bark


NumPy Starts Here

To make a Venv in python
python -m venv env_folder_name.\env\scripts\activate

In [27]:
import numpy as np
a=np.array([1,2,3,4])
b=np.zeros([3,3])
c=np.full([3,3],10)
f=np.linspace(0,1,5)
print(a)
print(b)
print(c)
print(f)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[0.   0.25 0.5  0.75 1.  ]


In [35]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("Type: ",arr.dtype)
print(arr.shape[0])
print(arr.shape[1])
reshaped=arr.reshape(3,2)
print(reshaped)
print(arr.flatten())


Shape:  (2, 3)
Dimension:  2
Size:  6
Type:  int64
2
3
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [44]:
#Indicing and Slicing
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0:2,1:3])
mask =arr>50

print(arr[mask])

[[20 30]
 [50 60]]
[60 70 80 90]


In [57]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x*y)
print(y/x)
print(x**2)
print(np.sqrt(x))
print(np.mean(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.sum(y,axis=0))
print(np.median(x))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]
[1.         1.41421356 1.73205081]
2.0
0.816496580927726
3
1
15
2.0


In [60]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([1,0,1])
print(a1+a2)

[[2 2 4]
 [5 5 7]]


In [62]:
from numpy import linalg as lg
M=np.array([[1,2],[3,4]])
print(M.T)
print(lg.det(M))
print(lg.inv(M))

[[1 3]
 [2 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [66]:
rand_arr=np.random.rand(3,3)
rand_ints=np.random.randint(1,10,(3,3))
normal_dist=np.random.normal(0,1,5)
print(rand_arr)
print(rand_ints)
print(normal_dist)

[[0.17416867 0.23934798 0.07074799]
 [0.98264961 0.09459134 0.92610087]
 [0.88597393 0.87528595 0.56561777]]
[[8 6 5]
 [7 8 1]
 [5 1 8]]
[ 0.50855616  2.06015538  1.04666685 -0.30259524  0.64809018]


HW=Study UTF encoding and Regex operations and how to create dataframe , total rows 50 . columns is 10, and data should be created by you only you